services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=YourStrongPassword1!
      - ACCEPT_EULA=Y
      - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
      - ./scripts:/initdb.d
    networks:
      - rede_projeto

networks:
  rede_projeto:
    driver: bridge
volumes:
  sqlserverdata:
